### ISSUE TITLE
Title of selected rule

### ISSUE THREAD

**Issue by tomdziwood** [dominieq/rule-work#47]
This title should contain also a condition part.

![obraz](https://user-images.githubusercontent.com/44382923/78470371-4d273100-7729-11ea-9cb2-49a51d008562.png)

**Comment by dominieq** [comment]
I will create standalone Component for title in this dialog.

**Comment by dominieq** [comment]
Done in commit [a9d8f37cab97a559a1c8d27be815bcab4ae0004f].
